### ISSUE TITLE
Support running as task daemon

### ISSUE THREAD

**Issue by adhocore** [adhocore/gronx#1]
draft API:

```go
taskr := gronx.NewTasker()

taskr.Task("*/5 * * * *", func (ctx Context) {
})
// ... add more tasks

// run tasker and triggers the task when each of them are due
taskr.Run()
```

**Comment by adhocore** [comment]
closed by #3

**Comment by lordofscripts** [comment]
Would be nice if it also had support for Start/Stop/Terminate. In that case the application could be installed as a service. Well, but also useful for user-controlled "daemons".

**Comment by adhocore** [comment]
yea that would be great indeed
