### ISSUE TITLE
NextTick method?

### ISSUE THREAD

**Issue by kokizzu** [adhocore/gronx#2]
it would be nice if there's `NextTick() -> time.Time` and `NextTickAfter(time.Time) -> time.Time` method that return nearest future that match the cron receiver

**Comment by adhocore** [comment]
yea thanks. that however is tricky for the way gronx now works. it is definitely in my attention though

**Comment by adhocore** [comment]
good news, it is being worked on and will be released in a few days

**Comment by adhocore** [comment]
https://github.com/adhocore/gronx/releases/tag/v1.1.0
