### ISSUE TITLE
Get LastTick of cron

### ISSUE THREAD

**Issue by n4n0lix** [adhocore/gronx#20]
A counter part to `NextTick` that doesn't look ahead, but backwards.

I am not aware of any cron parser for go that is capable of doing it. The only code out there that provides this is a fork of a fork of an abandoned project. This functionality would make a good USP.

**Comment by adhocore** [comment]
yea thanks, that should be possible given we already have similar NextTick. the main difference would be to backtrack instead.

**Comment by adhocore** [comment]
@n4n0lix would it be possible for you to review #22 briefly? thank.
i have chosen name `PrevTick` instead.

**Comment by n4n0lix** [comment]
Is your paypal.me link ( https://paypal.me/ji10 ) still up to date? Shows "no profile found" for me. Let me know once you updated it/when it works again.

**Comment by adhocore** [comment]
ohh paypal is really complex to use in where i am based, so had to disable it. if you are interested i'm on GitHub [sponsors](https://github.com/sponsors/adhocore). thanks
