### ISSUE TITLE
`NextTick` fails with `00 * * * *`

### ISSUE THREAD

**Issue by millotp** [adhocore/gronx#29]
Hi,

I encountered a weird situation where 
- `IsValid("00 * * * *")` is `true` and
- `NextTick("00 * * * *", false)` fails with the error `tried so hard`, but it works fine with `NextTick("0 * * * *", false)`

(it's the same with `00` in the hour segment)

I'm not sure which scenario is correct, because some cron validator online says this is valid and other don't,
so should `IsValid` return true or should `NextTick` work with this expression ? Thanks !

**Comment by adhocore** [comment]
thanks for ticket. 00 is wrong, no? i think 00 should be KO right away with error

**Comment by millotp** [comment]
It seems to work fine on [crontab.guru](https://crontab.guru/#00_*_*_*_*) and other website, in fact they accept any number of 0

**Comment by millotp** [comment]
If you want `IsValid` to be false for that case I can open a PR if you want

**Comment by adhocore** [comment]
yep, but what does the spec say? i ont know, need to look that up lol :D 
if 00 is equivalent to 0 then we can do so as per specification. if not we can error :)

**Comment by millotp** [comment]
According to most resources, leading zero are allowed but not required:
- The POSIX [specification](https://man.openbsd.org/crontab.5) doesn't mention anything
- This [stackoverflow](https://unix.stackexchange.com/a/579630) answer suggest that some systems fails to interpret leading zero
- ChatGPT thinks it's okay
```
Leading zeros can be used, but they are not required and have no impact on the cron expression's validity. For instance, 05, 5, and 0005 are all equivalent and valid for the minute field. The same applies to other fields as well
``` 

so I guess it's up to you 🤷‍♂️

**Comment by adhocore** [comment]
thanks it is more upto spec i think. :) i would appreciate a PR. 👍

(it was late yesterday in my timezone)
