### ISSUE TITLE
gracefully shutdown

### ISSUE THREAD

**Issue by lichunqiang** [adhocore/gronx#40]
> it exits gracefully when ctrl+c is received making sure pending tasks are completed.

if there is one task like `* * * * *`,  ctrl+c the program will hug on. 

how to understanding *pending tasks* ?

**Comment by adhocore** [comment]
the pending here means already in progress or already scheduled, i.e not yet finished

**Comment by adhocore** [comment]
i found that when running tasker **binary** as daemon, it immediately aborts the child process on ctrl+c, will be fixed by #41
