### ISSUE TITLE
Negative step possible in cron expression

### ISSUE THREAD

**Issue by sg3-141-592** [adhocore/gronx#44]
I've been trying out fuzzing gronx and have found you can set a negative step in a cron expression, e.g.

```0-0/-005 * * * *```

This negative step causes an infinite loop in [`inStepRange()`](https://github.com/adhocore/gronx/blob/28b4284153644ff3013b01570bc2a7c53f6eb60b/validator.go#L67)

Stepping through we can resolve by checking if `step <= 0`

https://github.com/adhocore/gronx/blob/28b4284153644ff3013b01570bc2a7c53f6eb60b/validator.go#L17

This is the fuzzer I was testing with

``` go
func FuzzValid(f *testing.F) {
	gron := New()

	// Add some seed inputs
	f.Add("* * * * *")
	f.Add("0 0 1 1 *")
	f.Add("*/15 0 1,15 * 1-5")

	f.Fuzz(func(t *testing.T, expr string) {
		_ = gron.IsValid(expr)
	})
}
```

**Comment by adhocore** [comment]
thanks for reporting. negative step is already invalid case so i think we can give out error right away here. your suggested fix is also fine, please send a PR, thank you
