### ISSUE TITLE
Windows Build Fails Because Of Using Linux Syscall

### ISSUE THREAD

**Issue by yeganemehr** [adhocore/gronx#47]
First of all, thank you for this project; it's a modern and excellent replacement for old crontab implementations on Linux distributions. I use `tasker` in most of my Docker containers, and I'm very happy with it.

----

When building gronx on Windows, there’s a build failure caused by a Linux-specific syscall in [tasker.go:127](https://github.com/adhocore/gronx/blob/89f74f2441582c0e29a81e1ea286b119a336bb98/pkg/tasker/tasker.go#L127) to create a process group ID (PGID).

```
pkg/tasker/tasker.go:127:42: unknown field Setpgid in struct literal of type syscall.SysProcAttr
```

Since this syscall only works on Unix-like systems, the build doesn’t complete successfully on Windows.

```go
exc := exec.Command(sh[0], sh[1], cmd)
exc.Stderr = &buf
exc.SysProcAttr = &syscall.SysProcAttr{Setpgid: true} # Linux Only
```

I’ve found a solution for Windows compatibility and will send a PR to fix this issue.

**Comment by adhocore** [comment]
glad to know that the project is of use to you :) 

thanks for the fix contribution 🎉
